package-lock.json
src/app/test/dropdown/menu/page.tsx

드롭다운메뉴 테스트 코드 변수명 일부(isDelete -> isDanger) 오류 수정
MEOW-62
수정이 덜 된 변수명만 네이밍 변경하였고, 나머지는 변경사항 없습니다.

[Fix] 드롭다운메뉴 테스트 코드 변수명 일부 오류 수정

---

src/app/profile/my-info/page.tsx
src/components/layout/navbar/BNB.tsx
src/types/input.types.ts

우선 폴더 구조 변경완료 했습니다.
폴더 구조를 빠르게 올려서 작업하는 게 좋을 것 같아 모바일 ui 구현을 대충해서 이 부분은 제가 나중에 수정할 예정입니다.
`/profile/my-info` 부분에 들어가주시면 확인하실 수 있습니다.
1. UI 구현
2. 폴더 구조 변경 profile 부분
JIRA: MEOW-124
issue: #69 
유효성 검사 코드는 멘토님께서 말씀하신 것도 있고 제가 생각하기에도 수정할 부분이 많을 거 같아서 주석처리 했습니다! 추후에 수정할 예정이니 이 부분은 확인 안하셔도 되고 모바일 ui만 확인 부탁드립니다.

[Feat] 모바일 ui 구현

---

src/app/test/modal/page.tsx
src/components/common/buttons/CloseButton.tsx
src/components/common/modals/AuthModal.tsx
src/components/common/modals/ConfirmModal.tsx
src/components/common/modals/CreateReviewModal.tsx
src/components/common/modals/Modal.tsx
src/components/common/modals/ReservationModal.tsx
src/components/common/modals/ReviewModal.tsx
src/components/providers/ModalProvider.tsx
src/hooks/useConfirmModal.tsx
src/hooks/useModal.tsx
src/types/confirm.types.ts
src/types/modal.types.ts
tailwind.config.js

- 모달 UI 공통 컴포넌트로 교체
- maring, padding, gap px로 수정
- 모달 훅 함수명 수정
- 모달 ReviewModal, ConfirmModal 수정 및 추가
- 모달 프롭 일부 수정
- 모달 데스크탑 -> 테블릿 브레이크포인트 수정
- ConfirmModal 분리
- useConfirmModal 훅 추가
리뷰 모달 프롭이나, 확인 모달 프롭은 필요한 값들로 수정 가능합니다.
`/test/modal` 페이지에서 테스트 가능합니다.
1. useModal 훅에서 가져와서 모달을 열 수 있습니다. 각자 필요한 모달도 추가 하실수 있습니다 밑에 예시 처럼.
```
// useModal.tsx
const openCreateReviewModal = (props: CreateReviewModalProps) => {
openModal({
header: '후기 작성',
children: <CreateReviewModal {...props} />, // 프롭, 모달 자유롭게 수정 가능
});
};
```
2. 필요한 페이지에서 함수를 만들어 openReviewModal와 같은 함수를 호출해 주세요
```
const { openCreateReviewModal, openConfirmModal } = useModal();
// 후기 모달 작성 예시
const handleCreateReview = () => {
openCreateReviewModal({
title: '함께 배우면 즐거운 스트릿 댄스',
schedule: { id: 1, date: '', startTime: '', endTime: '' }, …
```

[Refactor] 모달 훅 및 UI 수정

---

public/assets/icons/ico-plus.svg
src/app/profile/my-activities/components/NotFoundActivities.tsx
src/app/profile/my-activities/components/activity-management/ManagementCards.tsx
src/app/profile/my-activities/page.tsx
src/app/profile/my-activities/register/components/Category.tsx
src/app/profile/my-activities/register/components/RegisterForm.tsx
src/app/profile/my-activities/register/components/UploadImg.tsx
src/app/profile/my-activities/register/components/UploadImgList.tsx
src/app/profile/my-activities/register/components/register-calendar/RegisterCalendar.tsx
src/app/profile/my-activities/register/components/register-calendar/RegisterCalendarItem.tsx
src/app/profile/my-activities/register/page.tsx

체험 등록 UI 구현
- 이미지 업로드 표현
- 등록 버튼 구현 (등록하기 버튼을 누르면 router)
- 나머지 ui 
https://github.com/user-attachments/assets/fd65c8a0-d0d0-4155-8ecf-46fa895fc1b1
https://github.com/user-attachments/assets/0263b2b7-b930-4eef-bb39-287feef378b3
https://github.com/user-attachments/assets/47b464d1-bcc2-41a6-a2d7-353cfe76e1ea
https://github.com/user-attachments/assets/5a6d45d4-5746-4e02-b4ea-2e069b4dace1
1. `/profile/my-activities` 에서 새 체험 버튼을 클릭해보세요. /register로 페이지가 넘어갑니다.
2. `/profile/my-activities/register` 페이지에서 이미지를 업로드 해보세요. 이미지만 업로드 됩니다.(pdf, mov 업로드 안됩니다.)
3. 일정 추가할 때 일정들이 나오는 지 확인해주세요. 
ISSUE: #91 
JIRA: MEOW-150, MEOW-146, MEOW-154, MEOW-155
우선 **카테고리는 나중에 수정할 예정입니다!!** 컴포넌트 추가할 예정이라 임시로 만들어두었습니다.. 코드리뷰할 때 참고해 주세요 ^^b
등록 버튼도 ui 부분만 만들어 두었습니다.
다시 했습니다.. input과 textarea는 수정 이후에 다시 할 예정입니다.

[Feat] 체험 등록 UI 구현

---

src/app/profile/my-reservations/components/ReservationCalendar.tsx
src/app/profile/my-reservations/page.tsx
src/components/common/dropdowns/Dropdown.tsx
src/components/common/dropdowns/DropdownMenu.tsx
src/components/common/dropdowns/DropdownTrigger.tsx
src/components/common/modals/ReservationModal.tsx
src/types/dropdown-menu.types.ts
src/types/dropdown.types.ts

- Dropdown 에러사항 해결
- 트리거 여부
- 트리거 text 잘림
- 모바일 드롭다운 메뉴 안 보이는 현상
- z-index 수정
- 바텀시트의 경우, 뒷배경 스크롤 방지
- 바텀시트의 경우, title 명시
- 일정 메뉴의 크기 넘어갈 시, 스크롤 처리
- 수정된 Dropdown 토대로 예약 현황 dropdown 반영
https://github.com/user-attachments/assets/20ca53ec-6d46-45c7-ab49-d9910caba137
PC 버전 드롭다운
https://github.com/user-attachments/assets/ef1fc652-9eb7-40f6-ad95-f2a2228417db
모바일 버전 드롭다운
1. `profile/my-reservations` 예약 현황 페이지에 나온 드롭다운을 참고하여 활용
MEOW-

[Fix] Dropdown 에러사항 해결(트리거 여부, 트리거 text 잘림, etc)

---

package-lock.json
src/app/_components/PopularActivitiesBanner.tsx
src/app/_components/RecommendList.tsx
src/app/not-found.tsx
src/app/page.tsx
src/hooks/usePopularActivities.ts
src/types/activity.types.ts

- 404 페이지 추가
- 추천 체험 데이터 쿼리 훅 추가 `usePopularActivities.ts`
- 메인 페이지 추천 체험 데이터 패칭 `PopularActivitiesBanner.tsx` 컴포넌트로 이동
1. 존재 하지 않는 url로 이동
2. 404 페이지 출력
#171 
현재 activityCard 에서 이미지 오류나면 이미지

[Feat] 404 not-found 페이지

---

src/app/_components/RecommendList.tsx
src/middleware.ts

- 미들웨어 추가
- 로그인 상태에 `/account` 접근시 `/` 로 이동
- 로그인 상태 아닐시 `/profile` 접근시 `/account`로 이동
1.
2.
3.

[Feat] Middleware

---

src/lib/fetch/fetchFromClient.ts
src/lib/fetch/fetchFromServer.ts

- `fetchFromClient.ts` url path 문제 수정
1.
2.
3.

[Fix] 로그인 path 수정

---

src/services/userService.ts

[Fix] 프로필 API path 수정

---

src/components/common/modals/ConfirmModal.tsx
src/components/common/modals/Modal.tsx

[Fix] 스크롤 리턴 추가

---

src/app/profile/my-activities/[id]/edit/page.tsx
src/app/profile/my-activities/components/RegisterExperienceForm.tsx
src/app/profile/my-activities/components/skeleton-ui/SkeletonRegisterForm.tsx
src/app/profile/my-activities/register/page.tsx
src/app/profile/my-info/page.tsx
src/app/test/skeleton/page.tsx

1. `/test/skeleton` 에서 확인
2. `/profile/my-info` 에서 확인하실 수 있습니다. 
3. `/profile/my-activities/` 에서 수정하기 나 새 체험에서 확인하실 수 있습니다.

[Style] 스켈레톤 ui 구현

---

src/components/common/modals/CreateReviewModal.tsx
src/store/toastStore.ts

불필요한 Toast 컴포넌트 제외
1.
- 이미 처리되고 있어, 불필요한 Toast 컴포넌트는 삭제했습니다.
- 다만, UI적인 문제인지 중복으로 보이는 현상은 계속 됩니다.

[Refactor] 불필요한 Toast 컴포넌트 제외

---

package-lock.json
src/app/profile/analytics/monthly-pending-chart/MonthlyPendingChart.tsx
src/app/profile/analytics/page.tsx
src/app/profile/analytics/reservation-stats/ReservationLineChart.tsx
src/app/profile/analytics/reservation-stats/SummaryCards.tsx
src/app/profile/analytics/review-summary/MyActivitiesReviewList.tsx
src/app/profile/analytics/review-summary/MyActivityReviewCard.tsx
src/app/profile/analytics/review-summary/SkeletonReviewCard.tsx

- 컬러 팔레트에 맞는 색상 지정
- shadow 제거
- 표현 label 이름 통일
- 이번 달 체험별 예약 신청 현황 x축과 범례 간격 조정
- 리뷰 파트에서 / 대신 · (Middle dot)으로 변경
- 로딩 스피너 추가
전체 체험 예약 통계
이번 달 체험별 예약 신청 현황
체험별 리뷰 요약
1. 내 체험 통계 페이지
MEOW-203

[Feat] 통계 페이지 UI

---

package-lock.json
src/app/layout.tsx
src/app/profile/layout.tsx
src/app/profile/my-activities/components/activity-management/ManagementCard.tsx
src/app/profile/my-activities/components/activity-management/ManagementCards.tsx
src/app/profile/my-info/page.tsx
src/app/profile/reservations/components/ReservationsMain.tsx
src/hooks/useDeleteActivity.ts
src/hooks/useInfiniteActivities.ts

- 체험 카드 버블링 수정
- 삭제 API 주소 수정
1.
2.
3.

[Fix] 체험 카드 버블링 수정

---

src/app/activities/[id]/components/ExperienceDetailClient.tsx
src/app/activities/[id]/components/ExperienceResponsiveLayout.tsx
src/app/activities/[id]/components/common/ActivityDropdown.tsx
src/app/activities/[id]/components/common/ExperienceDetailSkeleton.tsx
src/app/activities/[id]/components/experience/ExperienceSummarySection.tsx
src/app/activities/[id]/components/reservation/ScheduleTimeItem.tsx
src/app/activities/[id]/components/reservation/ScheduleTimeSlot.tsx
src/app/activities/[id]/components/review/ReviewListModal.tsx
src/app/activities/[id]/page.tsx
src/app/profile/my-activities/components/register-calendar/RegisterCalendar.tsx
src/lib/fetch/fetchFromServer.ts
src/utils/response-helpers.ts

- `ExperienceDetailClient.tsx` 파일이 서버 컴포넌트로 변경
- 상세 페이지가 서버 컴포넌트로 변경
- `fetchFromServer` 파일 수정
1.
2.
3.
제대로 한 게 맞는지 아직 잘 모르겠습니다...... 확인 부탁드립니다......

[Refactor] 상세 페이지 SSR로 변경

---

src/components/common/buttons/BaseButton.tsx
src/components/common/modals/CreateReviewModal.tsx
src/constants/my-reservation-status.ts

- Textarea부분을 제외한 예약 내역 다크모드 입니다.
1.
2.
3.

[Style] 예약 내역 다크모드

---

src/app/profile/favorites/components/FavoritesList.tsx

- 찜목록에서 새로고침시 항목 없어지는 버그 수정
1.
2.
3.

[Fix] 찜목록 새로고침 수정

---

src/app/profile/my-activities/components/register-form/UploadImgList.tsx

- 이미지 업로드가 바로 안되는 버그 수정
1.
2.
3.

[Fix] 이미지 두번 클릭시 업로드

---

package-lock.json
src/app/activities/[id]/components/ExperienceResponsiveLayout.tsx
src/utils/my-activities-time 2.ts

- 상세 페이지 데스크탑 케밥 버튼 드롭다운 수정
https://github.com/user-attachments/assets/232fccee-8fca-4211-8576-a62306aeaf34
1.
2.
3.

[Fix] 데스크탑 드롭다운 수정

---

src/hooks/achievements/useCompletedCategories.ts

- 체험 완료 시 뱃지가 획득되지 않는 이슈 해결
1.
2.
3.
체험이 완료되고 내 업적 페이지 들어가면 뱃지 모달이 나오면서 미획득이 획득으로 변하는 것까지 확인했습니다.

[Fix] 뱃지 획득 안 되는 이슈 해결
